import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  content: {
    backgroundColor: "#F2F2F7",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 24,
    paddingHorizontal: 24,
    maxHeight: "90%",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  title: { fontSize: 22, fontWeight: "800", color: "#1C1C1E" },
  subTitle: { fontSize: 12, color: "#8E8E93", fontWeight: "600", marginTop: 2 },
  closeBtn: {
    width: 32,
    height: 32,
    backgroundColor: "#E5E5EA",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#8E8E93",
    letterSpacing: 1,
    marginBottom: 8,
    marginLeft: 8,
  },
  card: { backgroundColor: "#FFF", borderRadius: 16, overflow: "hidden" },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
  },
  borderTop: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E5E5EA",
  },
  rowLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  rowText: { fontSize: 16, fontWeight: "500", color: "#1C1C1E" },
  timeText: { fontSize: 14, color: "#8E8E93", fontWeight: "500" },
  timeBtnAndroid: {
    backgroundColor: "#F2F2F7",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  timeBtnTextAndroid: { fontSize: 16, fontWeight: "600", color: "#1C1C1E" },
  copyright: {
    textAlign: "center",
    fontSize: 12,
    color: "#C7C7CC",
    marginTop: 32,
    fontWeight: "600",
  },

  pinInputWrapper: {
    marginTop: 30,
    marginBottom: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  hiddenTextInput: {
    position: "absolute",
    width: "100%",
    height: "100%",
    opacity: 0,
    zIndex: 1,
  },
  pinDisplayContainer: { flexDirection: "row", gap: 15 },
  pinBox: {
    width: 55,
    height: 65,
    borderWidth: 1,
    borderRadius: 16,
    borderColor: "#C7C7CC",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFF",
  },
  pinBoxFocused: {
    borderColor: "#1C1C1E",
    borderWidth: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  pinDot: { fontSize: 36, color: "#1C1C1E" },

  subModalContent: {
    backgroundColor: "#FFF",
    width: "90%",
    alignSelf: "center",
    borderRadius: 20,
    padding: 24,
    marginBottom: "50%",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  inputField: {
    backgroundColor: "#F2F2F7",
    padding: 15,
    borderRadius: 12,
    marginTop: 15,
    fontSize: 16,
    fontWeight: "600",
    color: "#1C1C1E",
  },
  modalActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 20,
    gap: 15,
  },
  cancelText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#8E8E93",
    padding: 10,
  },
  saveBtn: {
    backgroundColor: "#1C1C1E",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
  },
  saveBtnText: { color: "#FFF", fontSize: 14, fontWeight: "700" },
  roomListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E5E5EA",
    gap: 10,
  },
  roomListText: { flex: 1, fontSize: 16, fontWeight: "600", color: "#1C1C1E" },
});
