// index.styles.ts
import { Dimensions, Platform, StyleSheet } from "react-native";

// 画面の横幅や縦幅を使っている場合のための準備
const { width, height } = Dimensions.get("window");


export const styles = StyleSheet.create({
    container: { flex: 1 },
    mainContent: { flex: 1, backgroundColor: "transparent" },
    calendarArea: { flex: 1, width: "100%" },
    weekCalendarWrapper: { height: 130 },
    monthLabel: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
      marginLeft: 20,
      marginTop: 10,
    },
    header: {
      paddingTop: Platform.OS === "ios" ? 10 : 65,
      paddingBottom: 20,
      paddingHorizontal: 24,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: "#F2F2F7",
    },
    headerTitleContainer: { alignItems: "flex-start" },
    headerPrefix: {
      fontSize: 10,
      fontWeight: "600",
      color: "#AEAEB2",
      letterSpacing: 2,
      marginBottom: 4,
      fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    },
    headerMainRow: { flexDirection: "row", alignItems: "center" },
    headerText: { fontSize: 18, fontWeight: "700", color: "#1C1C1E" },
    scheduleList: { flex: 1, padding: 15 },
    listPadding: { paddingBottom: 20 },
    dateTitle: {
      fontSize: 15,
      fontWeight: "bold",
      marginBottom: 12,
      color: "#666",
    },
    monthHeaderContainer: { width: "100%", alignItems: "flex-start" },
    monthformat: {
      fontSize: 28,
      paddingLeft: 10,
      paddingBottom: 5,
      fontWeight: "bold",
    },
  
    toggleContainer: {
      flexDirection: "row",
      backgroundColor: "#F2F2F7",
      borderRadius: 12,
      padding: 3,
      marginBottom: 10,
    },
    toggleBtn: {
      flex: 1,
      paddingVertical: 10,
      alignItems: "center",
      borderRadius: 10,
    },
    toggleItem: { flexDirection: "row", alignItems: "center", gap: 6 },
    toggleActive: {
      backgroundColor: "#fff",
      elevation: 2,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 3,
    },
    toggleText: { color: "#8E8E93", fontWeight: "bold", fontSize: 13 },
  
    todoRoot: { paddingHorizontal: 5 },
    modernHeader: { marginBottom: 20, marginTop: 5 },
    headerLabelRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      marginBottom: 8,
    },
    mainDateTitle: { fontSize: 20, fontWeight: "900", letterSpacing: -0.5 },
    numericProgress: { fontSize: 13, fontWeight: "600", color: "#8E8E93" },
    thinProgressBg: {
      height: 4,
      backgroundColor: "#E5E5EA",
      borderRadius: 2,
      overflow: "hidden",
    },
    thinProgressFill: { height: "100%", borderRadius: 2 },
    upcomingSection: {
      marginTop: 24,
      borderTopWidth: 1,
      borderTopColor: "#F2F2F7",
      paddingTop: 15,
    },
    upcomingMiniTitle: {
      fontSize: 12,
      fontWeight: "800",
      color: "#AEAEB2",
      marginBottom: 12,
      textTransform: "uppercase",
      letterSpacing: 1,
    },
  
    todoCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: "#F2F2F7",
      minHeight: 56,
    },
    todoCardDone: {
      backgroundColor: "transparent",
      borderColor: "transparent",
      opacity: 0.5,
    },
    stripeContainer: {
      flexDirection: "row",
      height: "60%",
      marginLeft: 8,
      gap: 2,
    },
    todoAccent: { width: 4, height: "100%", borderRadius: 2 },
    todoContent: { flex: 1, paddingVertical: 12, paddingHorizontal: 12 },
    todoMainRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    todoTitle: {
      fontSize: 15,
      fontWeight: "600",
      color: "#1C1C1E",
      flex: 1,
      marginRight: 8,
    },
    todoTitleDone: { color: "#8E8E93", textDecorationLine: "line-through" },
    miniTagBadge: {
      paddingHorizontal: 5,
      paddingVertical: 2,
      borderRadius: 4,
      borderWidth: 0.5,
    },
    miniTagText: { fontSize: 8, fontWeight: "bold" },
    todoSubRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 4,
      flexWrap: "wrap",
      gap: 6,
    },
    todoTimeRow: { flexDirection: "row", alignItems: "center", gap: 2 },
    todoTimeText: { fontSize: 10, color: "#8E8E93", fontWeight: "500" },
    checkButton: {
      paddingHorizontal: 10,
      paddingVertical: 10,
      justifyContent: "center",
      alignItems: "center",
    },
  
    deadlineBadgeUrgent: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#FF3B30",
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      shadowColor: "#FF3B30",
      shadowOpacity: 0.3,
      shadowRadius: 3,
      shadowOffset: { width: 0, height: 1 },
    },
    deadlineBadgeTextUrgent: {
      color: "#FFF",
      fontSize: 9,
      fontWeight: "900",
      letterSpacing: 0.5,
    },
    deadlineBadgeSafe: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#E5F9E7",
      borderWidth: 1,
      borderColor: "#34C759",
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
    },
    deadlineBadgeTextSafe: {
      color: "#34C759",
      fontSize: 9,
      fontWeight: "700",
    },
  
    listItem: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#fff",
      padding: 12,
      borderRadius: 10,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: "#F2F2F7",
    },
    itemTitle: { flex: 1, fontSize: 15, color: "#333", fontWeight: "bold" },
    tagBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
      marginBottom: 2,
    },
    tagText: { color: "#fff", fontSize: 9, fontWeight: "bold" },
    itemMain: {
      flex: 1,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    timeTextSmall: {
      fontSize: 10,
      color: "#8E8E93",
      fontWeight: "bold",
      marginLeft: 6,
    },
  
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.65)",
      justifyContent: "center",
      alignItems: "center",
    },
    filterModalContent: {
      width: "90%",
      height: "75%",
      backgroundColor: "#FFF",
      borderRadius: 28,
      padding: 24,
    },
    filterModalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 20,
    },
    filterModalTitle: { fontSize: 18, fontWeight: "700", color: "#1C1C1E" },
    filterModalSubTitle: {
      fontSize: 10,
      color: "#C7C7CC",
      textTransform: "uppercase",
    },
    gridScrollArea: { marginBottom: 20 },
    gridContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      gap: 10,
    },
    gridCard: {
      width: "48%",
      height: 70,
      paddingVertical: 16,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1.5,
    },
    gridCardGhost: { backgroundColor: "transparent", borderColor: "#F2F2F7" },
    gridCardText: { fontSize: 14, fontWeight: "700", textAlign: "center" },
    confirmBtn: { paddingVertical: 16, borderRadius: 16, alignItems: "center" },
    confirmBtnText: { color: "#FFF", fontSize: 16, fontWeight: "800" },
    modalSectionLabel: {
      fontSize: 9,
      fontWeight: "800",
      color: "#C7C7CC",
      letterSpacing: 1.5,
      fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    },
    presetContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 10,
    },
    presetBtn: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: "#F2F2F7",
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "#F2F2F7",
    },
    presetBtnText: { fontSize: 10, fontWeight: "700", color: "#8E8E93" },
    addPresetBtn: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: "#F2F2F7",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#C7C7CC",
      borderStyle: "dashed",
    },
    enhancedSettingsBtn: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F2F2F7",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      gap: 6,
    },
    settingsBtnLabel: {
      fontSize: 10,
      fontWeight: "800",
      fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    },
    sectionTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
  
    namingOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.8)",
      justifyContent: "center",
      alignItems: "center",
    },
    namingContent: {
      width: "80%",
      backgroundColor: "#FFF",
      borderRadius: 20,
      padding: 24,
    },
    namingLabel: {
      fontSize: 9,
      fontWeight: "800",
      color: "#C7C7CC",
      letterSpacing: 1.5,
      marginBottom: 4,
      fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    },
    namingTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: "#1C1C1E",
      marginBottom: 20,
    },
    namingInput: {
      backgroundColor: "#F2F2F7",
      padding: 16,
      borderRadius: 12,
      fontSize: 16,
      fontWeight: "600",
      color: "#1C1C1E",
      marginBottom: 20,
    },
    namingActionRow: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 16,
    },
    namingCancelBtn: { padding: 10 },
    namingCancelText: { fontSize: 12, fontWeight: "700", color: "#8E8E93" },
    namingConfirmBtn: {
      backgroundColor: "#1C1C1E",
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
    },
    namingConfirmText: { fontSize: 12, fontWeight: "700", color: "#FFF" },
    subTaskListContainer: {
      marginLeft: 20,
      paddingLeft: 12,
      borderLeftWidth: 2,
      borderLeftColor: "#E5E5EA",
      marginTop: 6,
      gap: 6,
    },
    subTaskMiniCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F8F8FA",
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 10,
    },
    subTaskMiniTitle: {
      fontSize: 13,
      fontWeight: "600",
      color: "#333",
      flex: 1,
    },
  
    pinInputWrapper: {
      marginTop: 10,
      marginBottom: 10,
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
    },
    hiddenTextInput: {
      position: "absolute",
      width: "100%",
      height: "100%",
      opacity: 0,
      zIndex: 1,
    },
    pinDisplayContainer: { flexDirection: "row", gap: 15 },
    pinBox: {
      width: 55,
      height: 65,
      borderWidth: 1,
      borderRadius: 16,
      borderColor: "#C7C7CC",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#FFF",
    },
    pinBoxFocused: {
      borderColor: "#1C1C1E",
      borderWidth: 2,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 5,
    },
    pinDot: { fontSize: 36, color: "#1C1C1E" },
  
    adContainer: {
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#fff",
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: "#E5E5EA",
      paddingBottom: Platform.OS === "ios" ? 0 : 5, // iPhoneのホームバー対策
    },
    summaryCard: {
      padding: 16,
      borderRadius: 16,
      borderWidth: 1,
      marginBottom: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
    },
    summaryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    summaryHeaderText: {
      fontSize: 12,
      fontWeight: "800",
      marginLeft: 6,
      letterSpacing: 0.5,
    },
    summaryTotalMini: {
      fontSize: 14,
      fontWeight: "900",
      marginRight: 8,
    },
    summaryDetailContainer: {
      marginTop: 12,
    },
    summaryDivider: {
      height: 1,
      backgroundColor: "#00000010",
      marginBottom: 12,
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    summaryItem: {
      alignItems: "flex-start",
    },
    summaryLabel: {
      fontSize: 9,
      fontWeight: "bold",
      color: "#8E8E93",
      marginBottom: 4,
    },
    summaryValue: {
      fontSize: 16,
      fontWeight: "900",
      color: "#1C1C1E",
    },
    unit: {
      fontSize: 10,
      fontWeight: "bold",
      marginLeft: 2,
    },
    emptyText: {
      textAlign: "center",
      color: "#8E8E93",
      fontSize: 15,
      fontWeight: "bold",
      marginTop: 40,
    },
  });
  