import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "94%",
    backgroundColor: "#fff",
    padding: 22,
    borderRadius: 25,
    // 🌟 変更：height を消して、minHeight と maxHeight にする
    minHeight: "55%",
    maxHeight: "85%",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold" },
  dateBadge: {
    backgroundColor: "#E5E5EA",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    fontSize: 12,
  },
  mainInput: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#1C1C1E",
  },
  timeSection: {
    backgroundColor: "#F8F8FA",
    padding: 12,
    borderRadius: 12,
    marginBottom: 15,
  },
  timePreviewRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    gap: 5,
  },
  timePreviewText: { fontSize: 13, fontWeight: "bold" },
  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  switchLabel: { fontSize: 14, color: "#1C1C1E", fontWeight: "600" },
  timePickerContainer: {
    borderTopWidth: 1,
    borderTopColor: "#EEE",
    paddingTop: 10,
  },
  timeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  timeLabel: { fontSize: 12, color: "#1C1C1E", fontWeight: "600" },
  label: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#666",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  layerContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 15,
  },
  layerChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: "#F2F2F7",
  },
  layerChipText: { fontSize: 12, color: "#666", fontWeight: "bold" },
  tagSection: { marginBottom: 15 },
  addTagCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F0F0F5",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },

  // 🌟 追加：新しい属性入力枠のスタイル
  newTagInput: {
    borderWidth: 1,
    borderRadius: 15,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    minWidth: 120,
    backgroundColor: "#FFF",
    fontSize: 12,
    fontWeight: "bold",
  },

  tagChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 15,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#EEE",
    marginRight: 8,
  },
  tagText: { fontSize: 12, fontWeight: "600" },
  optionSection: {
    backgroundColor: "#F8F8FA",
    padding: 12,
    borderRadius: 15,
    borderLeftWidth: 4,
    marginBottom: 15,
  },
  input: {
    backgroundColor: "#FFF",
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#EEE",
    marginTop: 10,
    color: "#1C1C1E",
    fontWeight: "bold",
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 15,
  },
  cancelBtn: { padding: 10 },
  saveBtn: { paddingHorizontal: 18, paddingVertical: 10, borderRadius: 12 },
  saveBtnText: { color: "#fff", fontWeight: "bold" },
  deleteBtn: {
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: "#EEE",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  deleteBtnText: { color: "#FF3B30", fontSize: 13, fontWeight: "bold" },
  suggestionWrapper: { marginBottom: 10, height: 32 },
  suggestionBadge: {
    backgroundColor: "#F2F2F7",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#DDD",
  },
  suggestionText: { fontSize: 12, color: "#333" },
  subTaskToggleBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderStyle: "dashed",
    marginTop: 10,
  },
  expandingInput: { marginTop: 15 },
  subTaskCard: {
    backgroundColor: "#FFF",
    padding: 12,
    borderRadius: 12,
    marginBottom: 10,
    borderLeftWidth: 5,
  },
  addSubTaskBtn: {
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
    marginTop: 5,
  },
  subTaskInput: {
    fontSize: 15,
    fontWeight: "600",
    flex: 1,
    color: "#333",
    paddingVertical: 5,
  },
  microChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "#F2F2F7",
  },
  modernDateBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
  },
  iosPickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  iosPickerContent: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  iosPickerHeader: {
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F5",
  },
  miniReminderChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E5EA",
  },
  customRepeatArea: {
    backgroundColor: "#F8F8FA",
    padding: 16,
    borderRadius: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#EEE",
  },
  miniLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#AEAEB2",
    textTransform: "uppercase",
  },
  daySelectorRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 20,
  },
  dayCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    backgroundColor: "#FFF",
    justifyContent: "center",
    alignItems: "center",
  },
  dayText: { fontSize: 12, fontWeight: "bold", color: "#8E8E93" },
  intervalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#EEE",
    paddingTop: 15,
  },
  intervalInput: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    borderRadius: 8,
    width: 50,
    textAlign: "center",
    paddingVertical: 4,
    fontSize: 16,
    fontWeight: "bold",
    color: "#1C1C1E",
  },

  simpleMainWrapper: {
    paddingHorizontal: 20,
    paddingBottom: 30,
    backgroundColor: "#FFF",
  },
  simpleDragBar: {
    width: 40,
    height: 5,
    backgroundColor: "#E5E5EA",
    borderRadius: 3,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  simpleHeroInput: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1C1C1E",
    marginVertical: 20,
    padding: 0, // 余計な余白をカット
  },
  simpleDateTimeCard: {
    backgroundColor: "#F2F2F7",
    borderRadius: 20,
    padding: 16,
    gap: 12,
    marginBottom: 20,
  },
  timePickerGroup: {
    flexDirection: "row",
    flex: 1,
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "wrap", // 小さい画面でもはみ出さないように
  },
  timeDivider: {
    height: 1,
    backgroundColor: "#E5E5EA",
    marginLeft: 32,
  },
  simpleActionRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  simpleOptBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 15,
    borderWidth: 1.5,
    borderColor: "#E5E5EA",
    backgroundColor: "#FFF",
  },
  simpleOptBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#8E8E93",
  },
  simpleAmountSection: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    backgroundColor: "#FFF9E6",
    padding: 15,
    borderRadius: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#FFCC0040",
  },
  amountSymbol: {
    fontSize: 24,
    fontWeight: "800",
    color: "#FFCC00",
    marginRight: 8,
  },
  simpleHeroAmountInput: {
    flex: 1,
    fontSize: 24,
    fontWeight: "800",
    color: "#1C1C1E",
  },
  miniCategoryScroll: {
    width: "100%",
    marginTop: 12,
  },
  miniChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#FFF",
    borderRadius: 10,
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#FFCC0040",
  },
  miniChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#FFCC00",
  },
  simpleBottomActions: {
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    marginTop: 10,
  },
  simpleDetailLink: {
    padding: 10,
  },
  simpleDetailLinkText: {
    fontSize: 15,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  simpleLargeSaveBtn: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  simpleLargeSaveBtnText: {
    color: "#FFF",
    fontSize: 17,
    fontWeight: "800",
  },
  timeLabelContainer: {
    width: 44, // 🌟 ここの幅を固定することで、上下のピッカーの位置が綺麗に揃います
    alignItems: "flex-start",
  },
  timeLabelText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#8E8E93",
  },

  // --- カテゴリ選択エリア用 ---
  simpleCategorySection: {
    marginBottom: 20,
  },
  simpleCategoryTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#8E8E93",
    marginBottom: 8,
    marginLeft: 4,
  },
  simpleCategoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#FFF",
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1.5,
    borderColor: "#E5E5EA",
  },
  simpleCategoryChipText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#8E8E93",
  },
});
